### ISSUE TITLE
ziffers-python couldn't import on windows 

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/ziffers-python#2]
I installed ziffers python on my computer with py -m pip install ziffers-python, and it was succesfull 
But i can't `import ziffers-python`

`  File "<console>", line 1
    import ziffers-python
                  ^
SyntaxError: invalid syntax`

I'm doing some tests for a windows configuration,
I'm running with python3.11 on my windows computer, sardine is working, but not ziffers.

**Comment by amiika** [comment]
Fixed some issues with music21 import. It should now be optional. Can you try to fetch it a gain and try "python -m pip install ." in the ziffers-python folder.

**Comment by amiika** [comment]
Ziffers is now installed on pypi: https://pypi.org/project/ziffers/0.0.1/ and can be installed using "pip -m install ziffers". Let me know if there is still some issues.
